FROM centos:7
MAINTAINER Ken Chen <simagix@gmail.com>
RUN yum -y install openldap compat-openldap openldap-clients openldap-servers openldap-servers-sql openldap-devel

ADD openldap/*.ldif /
ADD certs/ldap.simagix.com.pem /server.pem

EXPOSE 389 636
ADD entrypoint-ldap.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
