# Copyright 2019 Kuei-chun Chen. All rights reserved.
version: "3"

services:
  kerberos.simagix.com:
    image: simagix/kerberos
    hostname: kerberos.simagix.com
    environment:
      REALM: "SIMAGIX.COM"
      DOMAIN_REALM: "kerberos.simagix.com"
      ADMIN_USER: "admin"
      ADMIN_PASSWORD: "secret"
    volumes:
      - /tmp/kerberos:/var/log/kerberos
    restart: unless-stopped

  ldap.simagix.com:
    image: simagix/openldap
    hostname: ldap.simagix.com
    environment:
      ADMIN_PASSWORD: "secret"
    restart: unless-stopped

  mongo-gssapi.simagix.com:
    image: simagix/mongo-kerberos
    hostname: mongo-gssapi.simagix.com
    depends_on:
      - kerberos.simagix.com
      - ldap.simagix.com
    environment:
      REALM: SIMAGIX.COM
      ADMIN_USER: "admin"
      ADMIN_PASSWORD: "secret"
    command: /entrypoint.sh GSSAPI

  mongo-plain.simagix.com:
    image: simagix/mongo-kerberos
    hostname: mongo-plain.simagix.com
    depends_on:
      - mongo-gssapi.simagix.com
    environment:
      REALM: SIMAGIX.COM
    command: /entrypoint.sh PLAIN

  mongo-builtin.simagix.com:
    image: simagix/mongo-kerberos
    hostname: mongo-builtin.simagix.com
    depends_on:
      - mongo-gssapi.simagix.com
    command: /entrypoint.sh
networks:
  kerberos_net:
    driver: bridge
