# Copyright 2019 Kuei-chun Chen. All rights reserved.
version: "3"

services:
  kerberos:
    image: simagix/kerberos
    hostname: kerberos.simagix.com
    container_name: kerberos.simagix.com
    environment:
      REALM: SIMAGIX.COM
      DOMAIN_REALM: kerberos.simagix.com
      ADMIN_USER: admin
      ADMIN_PASSWORD: secret

  ldap:
    image: simagix/openldap
    hostname: ldap.simagix.com
    container_name: ldap.simagix.com
    environment:
      ADMIN_PASSWORD: secret

  mongo:
    image: simagix/mongo-kerberos
    hostname: mongo.simagix.com
    container_name: mongo.simagix.com
    depends_on:
      - kerberos
      - ldap
    environment:
      REALM: SIMAGIX.COM
      ADMIN_USER: admin
      ADMIN_PASSWORD: secret
    command: /entrypoint.sh server

  test:
    image: simagix/mongo-kerberos
    hostname: test.simagix.com
    container_name: test.simagix.com
    depends_on:
      - ldap
      - mongo
    environment:
      REALM: SIMAGIX.COM
      ADMIN_USER: admin
      ADMIN_PASSWORD: secret
    command: /entrypoint.sh test
