# Copyright 2019 Kuei-chun Chen. All rights reserved.
version: "3"

services:
  kerberos:
    image: simagix/kerberos
    hostname: kerberos.simagix.com
    container_name: kerberos.simagix.com
    environment:
      REALM: SIMAGIX.COM
      DOMAIN_REALM: kerberos.simagix.com
      ADMIN_USER: admin
      ADMIN_PASSWORD: secret
    volumes:
      - /tmp/kerberos:/var/log/kerberos
    restart: unless-stopped

  ldap:
    image: simagix/openldap
    hostname: ldap.simagix.com
    container_name: ldap.simagix.com
    environment:
      ADMIN_PASSWORD: secret
    restart: unless-stopped

  mongo-gssapi:
    image: simagix/mongo-kerberos
    hostname: mongo-gssapi.simagix.com
    container_name: mongo-gssapi.simagix.com
    depends_on:
      - kerberos
      - ldap
    environment:
      REALM: SIMAGIX.COM
      ADMIN_USER: admin
      ADMIN_PASSWORD: secret
    command: /entrypoint.sh GSSAPI
    restart: unless-stopped

  mongo-plain:
    image: simagix/mongo-kerberos
    hostname: mongo-plain.simagix.com
    container_name: mongo-plain.simagix.com
    depends_on:
      - ldap
    environment:
      REALM: SIMAGIX.COM
    command: /entrypoint.sh PLAIN
    restart: unless-stopped

  mongo:
    image: simagix/mongo-kerberos
    hostname: mongo.simagix.com
    container_name: mongo.simagix.com
    depends_on:
      - ldap
    command: /entrypoint.sh SCRAM
    restart: unless-stopped

  test:
    image: simagix/mongo-kerberos
    hostname: test.simagix.com
    container_name: test.simagix.com
    depends_on:
      - ldap
      - mongo
      - mongo-gssapi
      - mongo-plain
    environment:
      REALM: SIMAGIX.COM
    command: /entrypoint.sh test

networks:
  security_net:
    driver: bridge
