# Copyright 2019 Kuei-chun Chen. All rights reserved.
version: "3"

services:
  kerberos:
    image: simagix/kerberos
    hostname: kerberos
    environment:
      REALM: SIMAGIX.COM
      DOMAIN_REALM: kerberos.simagix.com
      ADMIN_USER: admin
      ADMIN_PASSWORD: secret

  ldap:
    image: simagix/openldap
    hostname: ldap
    environment:
      ADMIN_PASSWORD: secret

  mongo:
    image: simagix/mongo-kerberos
    hostname: mongo
    depends_on:
      - kerberos
      - ldap
    environment:
      REALM: SIMAGIX.COM
      ADMIN_USER: admin
      ADMIN_PASSWORD: secret
    command: /entrypoint.sh server

  test:
    image: simagix/mongo-kerberos
    hostname: test
    depends_on:
      - ldap
      - mongo
    environment:
      REALM: SIMAGIX.COM
      ADMIN_USER: admin
      ADMIN_PASSWORD: secret
    command: /entrypoint.sh test
